version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  node:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - mongo
